M48
; DRILL file {KiCad 8.0.2} date 2025-03-01T20:33:08+0100
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-03-01T20:33:08+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0354
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0394
%
G90
G05
T1
X5.2624Y-3.2802
X5.2624Y-3.4534
T2
X3.7848Y-2.7618
X4.099Y-2.7618
M30
